### ISSUE TITLE
FatalErrorException in ByteFormatterExtension.php line 0:

### ISSUE THREAD

**Issue by murali565** [xelan/resque-webui-bundle#5]
Hi Team,

I get this error:

FatalErrorException in ByteFormatterExtension.php line 0:
Error: Class Andaris\ResqueWebUiBundle\Twig\ByteFormatterExtension contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Twig_ExtensionInterface::getName)

![image](https://user-images.githubusercontent.com/55405110/115542975-7d9f2600-a2be-11eb-9ea9-3fe3728b3ce2.png)

composer show:

![image](https://user-images.githubusercontent.com/55405110/115543076-9c9db800-a2be-11eb-8add-e13b9d8d4805.png)

Can you please help me fix this error. Thanks.

**Comment by xelan** [comment]
Hi @murali565! Your twig version 1.23.1 is very old (released 2015), unsupported and [contains security vulnerabilities](https://packagist.org/packages/twig/twig/advisories?version=574857). Please update to the latest supported Twig 1.x version `v1.44.2` and try again.

**Comment by xelan** [comment]
Starting from 1.26, Twig should work according to the [docs](https://twig.symfony.com/doc/1.x/deprecated.html#extensions)
